apiVersion: apps/v1
kind: Deployment
metadata:
  name: barad-dur
  namespace: mordor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barad-dur
  template:
    metadata:
      labels:
        app: barad-dur
        faction: sauron
    spec:
      containers:
      - name: barad-dur
        image: "docker.io/ealen/echo-server"
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: barad-dur
  namespace: mordor
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: barad-dur