apiVersion: apps/v1
kind: Deployment
metadata:
  name: deathstar
  namespace: empire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deathstar
  template:
    metadata:
      labels:
        app: deathstar
        org: empire
    spec:
      containers:
      - name: deathstar
        image: "docker.io/ealen/echo-server"
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deathstar
  namespace: empire
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: deathstar
