apiVersion: apps/v1
kind: Deployment
metadata:
  name: nazgul
  namespace: mordor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nazgul
  template:
    metadata:
      labels:
        app: nazgul
        faction: sauron
        race: nazgul
    spec:
      containers:
      - name: nazgul
        image: curlimages/curl:8.4.0
        command: ["sleep", "3600"]