apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobbit
  namespace: mordor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobbit
  template:
    metadata:
      labels:
        app: hobbit
        faction: free-peoples
        race: hobbit
    spec:
      containers:
      - name: hobbit
        image: curlimages/curl:8.4.0
        command: ["sleep", "3600"]