apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "protect-deathstar-exhaust-port"
  namespace: empire
spec:
  endpointSelector:
    matchLabels:
      app: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        class: imperial
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/v1/exhaust-port"
