#!/bin/bash
#
# 🔑 Age Key Generator for SOPS
# Building Secure Dev Environments with Ubuntu on WSL
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
NC='\033[0m'
BOLD='\033[1m'

# ASCII Art
echo -e "${CYAN}"
cat << 'EOF'
    ╔═══════════════════════════════════════════════════════════╗
    ║                                                           ║
    ║     █████╗  ██████╗ ███████╗    ██╗  ██╗███████╗██╗   ██╗ ║
    ║    ██╔══██╗██╔════╝ ██╔════╝    ██║ ██╔╝██╔════╝╚██╗ ██╔╝ ║
    ║    ███████║██║  ███╗█████╗      █████╔╝ █████╗   ╚████╔╝  ║
    ║    ██╔══██║██║   ██║██╔══╝      ██╔═██╗ ██╔══╝    ╚██╔╝   ║
    ║    ██║  ██║╚██████╔╝███████╗    ██║  ██╗███████╗   ██║    ║
    ║    ╚═╝  ╚═╝ ╚═════╝ ╚══════╝    ╚═╝  ╚═╝╚══════╝   ╚═╝    ║
    ║                                                           ║
    ║           🔐 Modern Encryption for Secrets 🔐             ║
    ║                                                           ║
    ╚═══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

echo -e "${YELLOW}🐇 'Follow the white rabbit...' - Trinity${NC}\n"
sleep 1

# Check if age is installed
if ! command -v age-keygen &> /dev/null; then
    echo -e "${RED}❌ 'age' is not installed!${NC}"
    echo -e "${CYAN}Installing age...${NC}"
    
    # Install age
    sudo apt-get update && sudo apt-get install -y age
    
    echo -e "${GREEN}✅ age installed successfully!${NC}"
fi

# Define key location
KEY_DIR="${HOME}/.sops"
KEY_FILE="${KEY_DIR}/key.txt"

echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}▶ Generating Age Key${NC}"
echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

# Create directory if it doesn't exist
mkdir -p "${KEY_DIR}"
chmod 700 "${KEY_DIR}"

# Check if key already exists
if [ -f "${KEY_FILE}" ]; then
    echo -e "${YELLOW}⚠️  Key already exists at ${KEY_FILE}${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${CYAN}ℹ️  Keeping existing key.${NC}"
        exit 0
    fi
fi

# Generate the key
age-keygen -o "${KEY_FILE}" 2>&1 | tee /tmp/age-keygen-output.txt
chmod 600 "${KEY_FILE}"

# Extract public key
PUBLIC_KEY=$(grep "public key:" /tmp/age-keygen-output.txt | awk '{print $NF}')
rm /tmp/age-keygen-output.txt

echo -e "\n${GREEN}✅ Age key generated successfully!${NC}"
echo -e "${CYAN}📁 Private key: ${KEY_FILE}${NC}"
echo -e "${CYAN}🔑 Public key:  ${PUBLIC_KEY}${NC}"

# Export environment variable
echo -e "\n${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}▶ Setting Environment Variables${NC}"
echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

export SOPS_AGE_KEY_FILE="${KEY_FILE}"
export SOPS_AGE_RECIPIENTS="${PUBLIC_KEY}"

# Add to bashrc if not present
if ! grep -q "SOPS_AGE_KEY_FILE" ~/.bashrc 2>/dev/null; then
    echo "" >> ~/.bashrc
    echo "# SOPS Age encryption key" >> ~/.bashrc
    echo "export SOPS_AGE_KEY_FILE=\"${KEY_FILE}\"" >> ~/.bashrc
    echo -e "${GREEN}✅ Added SOPS_AGE_KEY_FILE to ~/.bashrc${NC}"
fi

# Create .sops.yaml config
SOPS_CONFIG=".sops.yaml"
cat > "${SOPS_CONFIG}" << EOF
# SOPS Configuration
# Generated by generate-age-key.sh
creation_rules:
  - path_regex: .*secrets.*\.yaml$
    age: ${PUBLIC_KEY}
EOF

echo -e "${GREEN}✅ Created ${SOPS_CONFIG} configuration${NC}"

# Summary
echo -e "\n${GREEN}"
cat << 'EOF'
    ╔═══════════════════════════════════════════════════════════╗
    ║                                                           ║
    ║   🎉 KEY GENERATION COMPLETE! 🎉                          ║
    ║                                                           ║
    ║   Next Steps:                                             ║
    ║   1. Source your bashrc: source ~/.bashrc                 ║
    ║   2. Encrypt secrets: ./encrypt-in-place.sh               ║
    ║                                                           ║
    ║   ⚠️  NEVER commit key.txt to version control!            ║
    ║                                                           ║
    ╚═══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

echo -e "${YELLOW}🔮 'The key to the Matrix is choice.' - The Architect${NC}\n"
