#!/bin/bash
#
# Age Key Generator for SOPS
# UbuCon Africa 2026 Workshop
#
# Supports: Linux, macOS, WSL
#

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${CYAN}"
echo "======================================================"
echo "     Age Key Generator for SOPS"
echo "     UbuCon Africa 2026 Workshop"
echo "======================================================"
echo -e "${NC}"

# Detect OS
detect_os() {
    case "$(uname -s)" in
        Linux*)  echo "linux" ;;
        Darwin*) echo "macos" ;;
        *)       echo "unknown" ;;
    esac
}

OS=$(detect_os)
echo -e "${CYAN}[INFO] Detected OS: $OS${NC}"

# Check if age is installed, install if not
if ! command -v age-keygen &> /dev/null; then
    echo -e "${YELLOW}[INFO] 'age' is not installed. Installing...${NC}"
    
    case $OS in
        linux)
            if command -v apt-get &> /dev/null; then
                sudo apt-get update && sudo apt-get install -y age
            elif command -v dnf &> /dev/null; then
                sudo dnf install -y age
            elif command -v pacman &> /dev/null; then
                sudo pacman -S age
            else
                echo -e "${RED}[ERROR] Could not detect package manager. Please install 'age' manually.${NC}"
                exit 1
            fi
            ;;
        macos)
            if command -v brew &> /dev/null; then
                brew install age
            else
                echo -e "${RED}[ERROR] Homebrew not found. Please install 'age' manually.${NC}"
                exit 1
            fi
            ;;
        *)
            echo -e "${RED}[ERROR] Unsupported OS. Please install 'age' manually.${NC}"
            exit 1
            ;;
    esac
    
    echo -e "${GREEN}[OK] age installed successfully!${NC}"
fi

# Define key location
KEY_DIR="${HOME}/.sops"
KEY_FILE="${KEY_DIR}/key.txt"

echo -e "\n${CYAN}>>> Generating Age Key${NC}\n"

# Create directory if it doesn't exist
mkdir -p "${KEY_DIR}"
chmod 700 "${KEY_DIR}"

# Check if key already exists
if [ -f "${KEY_FILE}" ]; then
    echo -e "${YELLOW}[WARN] Key already exists at ${KEY_FILE}${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${CYAN}[INFO] Keeping existing key.${NC}"
        
        # Still export the public key
        PUBLIC_KEY=$(grep "public key:" "${KEY_FILE}" | awk '{print $NF}')
        echo -e "${CYAN}Public key: ${PUBLIC_KEY}${NC}"
        exit 0
    fi
fi

# Generate the key
age-keygen -o "${KEY_FILE}" 2>&1 | tee /tmp/age-keygen-output.txt
chmod 600 "${KEY_FILE}"

# Extract public key
PUBLIC_KEY=$(grep "public key:" /tmp/age-keygen-output.txt | awk '{print $NF}')
rm /tmp/age-keygen-output.txt

echo -e "\n${GREEN}[OK] Age key generated successfully!${NC}"
echo -e "${CYAN}Private key: ${KEY_FILE}${NC}"
echo -e "${CYAN}Public key:  ${PUBLIC_KEY}${NC}"

# Export environment variable
echo -e "\n${CYAN}>>> Setting Environment Variables${NC}\n"

export SOPS_AGE_KEY_FILE="${KEY_FILE}"
export SOPS_AGE_RECIPIENTS="${PUBLIC_KEY}"

# Detect shell config file
if [ -n "${ZSH_VERSION:-}" ] || [ -f "$HOME/.zshrc" ]; then
    SHELL_RC="$HOME/.zshrc"
else
    SHELL_RC="$HOME/.bashrc"
fi

# Add to shell config if not present
if ! grep -q "SOPS_AGE_KEY_FILE" "$SHELL_RC" 2>/dev/null; then
    echo "" >> "$SHELL_RC"
    echo "# SOPS Age encryption key" >> "$SHELL_RC"
    echo "export SOPS_AGE_KEY_FILE=\"${KEY_FILE}\"" >> "$SHELL_RC"
    echo -e "${GREEN}[OK] Added SOPS_AGE_KEY_FILE to $SHELL_RC${NC}"
fi

# Create .sops.yaml config
SOPS_CONFIG=".sops.yaml"
cat > "${SOPS_CONFIG}" << EOF
# SOPS Configuration
# Generated by generate-age-key.sh
creation_rules:
  - path_regex: .*secrets.*\.yaml$
    age: ${PUBLIC_KEY}
EOF

echo -e "${GREEN}[OK] Created ${SOPS_CONFIG} configuration${NC}"

# Summary
echo -e "\n${GREEN}======================================================${NC}"
echo -e "${GREEN}     Key Generation Complete!${NC}"
echo -e "${GREEN}======================================================${NC}"
echo ""
echo "Next Steps:"
echo "  1. Source your shell config: source $SHELL_RC"
echo "  2. Encrypt secrets: ./encrypt-in-place.sh"
echo ""
echo -e "${RED}WARNING: NEVER commit key.txt to version control!${NC}"
echo ""
